name: 🐛 Bug report
description: Create a report to help us improve Harmonix
body:
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a minimal reproduction of the issue.
      placeholder: Reproduction
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Additional context
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected behavior
