name: ⬆️ update

on:
  workflow_run:
    workflows: [🚀 release]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          repository: harmonix-js/starter
          ref: main
          token: ${{secrets.ACTION_GITHUB_TOKEN}}
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
      - run: npm install
      - name: Update dependencies
        run: |
          npm install @harmonix-js/core@latest
          npm install -D @harmonix-js/cli@latest
      - name: Commit changes
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}
          git commit -am "chore(deps): update dependencies" || echo "No changes to commit"
          git push
