name: ⬆️ update

on:
  workflow_run:
    workflows: [🚀 release]
    types:
      - completed

jobs:
  update:
    strategy:
      matrix:
        include:
          - repository: harmonix-js/starter
            dependencies:
              install: '@harmonix-js/core'
              dev: '@harmonix-js/cli'
          - repository: harmonix-js/cli
            dependencies:
              install: '@harmonix-js/core'
              dev: ''

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          repository: ${{matrix.repository}}
          ref: main
          token: ${{secrets.ACTION_GITHUB_TOKEN}}
      - run: corepack enable
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install --no-frozen-lockfile
      - name: Update dependencies
        run: |
          pnpm add ${{matrix.dependencies.install}}@latest
          if [ -n "${{matrix.dependencies.dev}}" ]; then
            pnpm add -D ${{matrix.dependencies.dev}}@latest
          fi
      - name: Commit changes
        run: |
          git config user.email ${{secrets.EMAIL}}
          git config user.name ${{secrets.NAME}}
          git commit -am "fix: update dependencies" || echo "No changes to commit"
          git push
